// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVl935AJJ9iK8rKpH7Jp2Bu_13TLK4Nh8',
    appId: '1:742403378883:web:65037235615ee1a9f79c76',
    messagingSenderId: '742403378883',
    projectId: 'bhudipuja-38071',
    authDomain: 'bhudipuja-38071.firebaseapp.com',
    storageBucket: 'bhudipuja-38071.appspot.com',
    measurementId: 'G-VDY8BMXRVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-GuDy8-EJhUH6PZXdnbylb95eLIGxtCQ',
    appId: '1:742403378883:android:b2616cd5efd2a9e7f79c76',
    messagingSenderId: '742403378883',
    projectId: 'bhudipuja-38071',
    storageBucket: 'bhudipuja-38071.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD38mvqcQlTq-vmogJeOhuX83bdCg_-NU',
    appId: '1:742403378883:ios:76ce4fe60d05b949f79c76',
    messagingSenderId: '742403378883',
    projectId: 'bhudipuja-38071',
    storageBucket: 'bhudipuja-38071.appspot.com',
    iosBundleId: 'com.example.sellerApp',
  );
}
